linters:
  # Disable all linters.
  # Default: false
  # Enable specific linter
  # https://golangci-lint.run/usage/linters/#enabled-by-default-linters
  # Enable all available linters.
  # Default: false
  enable-all: false

